### ISSUE TITLE
Logistics slots cleared after return from Spectate mode

### ISSUE THREAD

**Issue by JuicyJuuce** [3RaGaming/utils#6]
To reproduce:
1. Be an admin
2. Set up at least one logistics request in your Logistics inventory tab.
3. Press the Spectate button on the Admin Tools GUI.
4. Press the Return button
5. Observe that all logistics requests are missing.

**Comment by zackman0010** [comment]
Check my comment on Pull Request #7

**Comment by zackman0010** [comment]
Thanks for the fix
